django_login_page_using_mysql/dprojx/dappx/urls.py
from django.conf.urls import url
from dappx import views

# SET THE NAMESPACE!

app_name = 'dappx'

# Be careful setting the name to just /login use userlogin instead!

urlpatterns=[
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/', views.user_login, name='user_login'),
]

django_login_page_using_mysql/dprojx/dprojx/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from django.conf.urls import url,include
from dappx import views
from django.conf import settings
from django.conf.urls.static import static

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^special/', views.special, name='special'),
    url(r'^dappx/', include('dappx.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    
    #password reset links:
    # path('password_change/done', auth_views.PasswordChangeDoneView.as_view(), name= 'password_change_done'),

    # path('password_change/', auth_views.PasswordChangeView.as_view(),name= 'password_change'),
    
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name= 'dappx/password_reset_done.html'), name= 'password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name= 'password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name= 'dappx/password_reset.html'), name= 'password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name= 'dappx/password_reset_complete.html'), name= 'password_reset_complete')

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_login_page_using_mysql/dprojx/dappx/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
      return self.user.username

django_login_page_using_mysql/dprojx/dappx/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class userform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('first_name','last_name','username','password','email','is_staff','is_superuser')

class userprofileinfoform(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ['portfolio_site', 'profile_pic']

django_login_page_using_mysql/dprojx/dappx/views.py
from django.shortcuts import render
from dappx.forms import userform,userprofileinfoform
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request,'dappx/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = userform(data=request.POST)
        profile_form = userprofileinfoform(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            password = user_form.cleaned_data['password']
            user.set_password(password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = userform(data=request.GET)
        profile_form = userprofileinfoform(data=request.GET)
    return render(request,'dappx/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print ({"username":username,"password":password})
        user = authenticate(request, username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'dappx/login.html', {})

django_login_page_using_mysql/dprojx/templates/dappx/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Base</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

<body>
	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<ul class="nav navbar-nav">
				<!-- {# Django Home Link / Admin Link / Register Link#} -->
				<li>
					<a class="navbar-brand" href="{% url 'index' %}">Home</a>
				</li>
				<li>
					<a class="navbar-link" href="{% url 'admin:index' %}">Admin</a>
				</li>
				<li>
					<a class="navbar-link" href="{% url 'dappx:register' %}">Register</a>
				</li>
<!-- 		    {# Some logic on what to display for last item#} -->
                {% if user.is_authenticated %}
                <li>
                	<a href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li>
                	<a class="navbar-link" href="{% url 'dappx:user_login' %}">Login</a>
                </li>
                {% endif %}				
			</ul>
		</div>
	</nav>
	<div class="container">
	    {% block body_block %}
	    {% endblock %}
    </div>
</body>
</html>

django_login_page_using_mysql/dprojx/templates/dappx/header.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Password_reset_process</title>
  </head>
 <body>

    {% block content %}

    {% endblock %} 
      
  </body>
</html>

django_login_page_using_mysql/dprojx/templates/dappx/index.html
{% extends "dappx/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Page !</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2>Register or Login if you'd like to</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

django_login_page_using_mysql/dprojx/templates/dappx/login.html
{% extends 'dappx/base.html' %}
{% block body_block %}

<div class="container">
	<div class="jumbotron">
	  <h1>Login here :</h1>
		<form method="post" action="{% url 'dappx:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
   		    <label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
          <input type="submit" name="" value="Login">
          <a href="{% url 'password_reset' %}">Forget Password?<i class="mdi mdi-key-change:"></i></a>
          
		</form>
	</div>
 </div>

{% endblock %}

django_login_page_using_mysql/dprojx/templates/dappx/password_change.html
{% extends 'dappx/base.html' %}

{% block content %}
<style type="text/css">
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
  }
  .form-signin .checkbox {
    font-weight: 400;
  }
  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="password"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .h3{
    text-align: center;
  }
</style>


<form method="POST" class="form-signin">{% csrf_token %}
  <h1 class="h3 mb-3 font-weight-normal">Change password</h1>
    <input name="old_password" class="form-control" placeholder="Old password" type="password" id="id_old_password" required="true">
    <input name="new_password1" class="form-control" placeholder="New password" type="password" id="id_new_password1" required="true">
    <input name="new_password2" class="form-control" placeholder="Confirm password" type="password" id="id_new_password2" required="true">

    {% for field in form %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    {% endfor %}

  <button class="btn btn-lg btn-primary btn-block" type="submit">Update</button>  
</form>



{% endblock %}

django_login_page_using_mysql/dprojx/templates/dappx/password_change_done.html
{% extends 'dappx/base.html' %}

{% block content %}

<div class="container">
	<div class="d-flex flex-column">
		<p class="m-auto">Your password has been Updated.</p>
	</div>
</div>

{% endblock %}

django_login_page_using_mysql/dprojx/templates/dappx/password_reset.html
<!DOCTYPE html>
<html>
<head>
	<title>Reset your password</title>
</head>
<body>
    <h3>Password reset</h3>

    <p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

    <form method="post">

    	{% csrf_token %}
    	{{form}}
    	<input type="Submit" name="Send email">
    	
    </form>
</body>
</html>

django_login_page_using_mysql/dprojx/templates/dappx/password_reset_complete.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
    <div class="container">
    	<div class="d-flex flex-column">
    		<p class="m-auto">Your password has been reset. You may go ahead and <a href="{% url 'dappx:user_login' %}">sign in</a> now.</p>
    	</div>
    </div>
</body>
</html>

django_login_page_using_mysql/dprojx/templates/dappx/password_reset_done.html
{% block content %}

<div class="container">

	<div class="d-flex flex-column">
		  <p class="m-auto p-2">
		    We've emailed you instructions for setting your password, if an account exists with the email you entered.
		    You should receive them shortly.
		  </p>
		  <p class="m-auto p-2">
		    If you don't receive an email, please make sure you've entered the address you registered with,
		    and check your spam folder.
		  </p>
		  <p class="m-auto p-2"><a href="{% url 'dappx:user_login' %}">Return to home page</a></p>
	</div>
</div>

{% endblock %}

django_login_page_using_mysql/dprojx/templates/dappx/password_reset_email.html
  
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The Technical Team
{% endautoescape %}

django_login_page_using_mysql/dprojx/templates/dappx/registration.html
{% extends "dappx/base.html" %}
{% load static %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for registering!</h1>
    {% else %}
      <h1>Register Here</h1>
      <h3>Just fill out the form.</h3>
      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
      </form>
    {% endif %}
  </div>
</div>
{% endblock %}